### ISSUE TITLE
Why having .el in your project name

### ISSUE THREAD

**Issue by michaelsjackson** [mtekman/org-treeusage.el#10]
A bit strange, not?
.el, where is should be only org-treeusage, and not org-treeusage.el, I mean this project name, not file name.

**Comment by mtekman** [comment]
It's a very common convention.

See the elisp repositories from

 https://github.com/magnars

Or

https://github.com/alphapapa

**Comment by michaelsjackson** [comment]
I see, thanks for clarification, in Magnar's case yes, in alphapapa's case kind of not always, ok now I know this can be "standard way", kind of.  Have a nice day my friend.
