### ISSUE TITLE
Link to org-du (similar project)

### ISSUE THREAD

**Issue by novoid** [mtekman/org-treeusage.el#2]
Hi @mtekman, 

Thanks for your project.

I once made a public hack to mis-use "du" for the same purpose. You solution is much nicer with respect to Emacs integration and dependencies to external tools.

However, if you want to provide your users the graphical alternative with my workaround, I'd be happy to see a "Similar projects" heading in your readme just as I did with mine: https://github.com/novoid/org-du#similar-projects

If not, no hard feelings - just close this issue.

**Comment by mtekman** [comment]
Just committed -- let me know if you want to adjust the wording!

**Comment by novoid** [comment]
Thanks for the pointer. Let's make sure everyone gets the workflow she is looking for.

**Comment by novoid** [comment]
Oh, I've just realized that you lined to https://github.com/novoid/org-du/tree/master/orgdu instead of the project landing page https://github.com/novoid/org-du

The difference is that the latter shows the README file whereas the first one shows only the code file. Could you please change to the link that goes to the landing page of the project?

**Comment by mtekman** [comment]
Whoops, fixed now https://github.com/mtekman/org-treeusage.el/commit/707be8761e4faeae25f832467923a05c593768a8
