### ISSUE TITLE
Feature: Colorize headlines based off of content percentages. 

### ISSUE THREAD

**Issue by progfolio** [mtekman/org-treeusage.el#3]
Might be nice to have some configurable way to that colorize each headline within overall percentage ranges. It would give a quick visual indicator of which headlines are "hot".

**Comment by mtekman** [comment]
Good idea -- I might be able to implement this soon!

**Comment by mtekman** [comment]
Fixed in v0.3 https://github.com/mtekman/org-treeusage.el/commit/451fa3fab97731478d72c4f27115979c3a732b4a

@progfolio  Let me know if the new version works for you :+1:
